name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: stonedDiscord/build-godot-action@patch-1
        with:
          name: client
          preset: windows
          projectDir: "CC Client"
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - Windows
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: stonedDiscord/build-godot-action@patch-1
        with:
          name: client
          preset: windows
          projectDir: "CC Server"
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Server - Windows
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
